### ISSUE TITLE
xml.etree.ElementTree.ParseError: no element found: line 2, column 0

### ISSUE THREAD

**Issue by hrnciar** [hrnciar/diplomka#11]
~~~~
$ ./uredni-deska.py -sid 50 -eid 50
Traceback (most recent call last):
  File "./uredni-deska.py", line 97, in <module>
    date, filename = get_data(id)
  File "./uredni-deska.py", line 42, in get_data
    root = ET.fromstring(request.text)
  File "/usr/lib64/python3.7/xml/etree/ElementTree.py", line 1316, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 2, column 0
~~~~

**Comment by hrnciar** [comment]
Fixed in https://github.com/hrnciar/diplomka/commit/ca48f734cacfb9a9200c5f4d65ad9eaea86895a5
